# General
KMER: 6
SPECIE: "hCoV-19"

# Undersample sequences
PATH_FASTA_GISAID: "/home/disco/Data/GISAID/sequences_aux.fasta"
PATH_METADATA: "/home/disco/Data/GISAID/metadata_aux.tsv"
CLADES: ['S','L','G','V','GR','GH','GV','GRY']
SAMPLES_PER_CLADE: 5000

# For training
TRAIN_SIZE: 0.8 # size for val and test sets: (1-TRAIN_SIZE)/2
BATCH_SIZE: 16
EPOCHS: 50
# MODEL: f"resnet50_{KMER}mers"
PREPROCESSING: {"divide_by_max": {},"a":{}} # ("name_function", dict_kwargs)
WEIGHTS_PATH: None
SEED: 42

# FOLDER_FASTA: f"data/{SPECIE}",
# FOLDER_FCGR: f"fcgr-{KMER}-mer",